import "@/styles/globals.css";

import { type Metadata } from "next";
import { Figtree } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import Nav from "./_components/Nav";
import Providers from "./_components/Providers";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${figtree.variable}`}>
      <body>
        <TRPCReactProvider>
          <Providers>
            <Nav />
            <main className="p-4">{children}</main>
          </Providers>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
